/**
 * TypeScript type generation — generates interfaces from content type schemas.
 */

import { join } from 'node:path';
import { mkdirSync, writeFileSync } from 'node:fs';
import type { CliCommand } from '../cli.js';
import { success, info, error as logError } from '../colors.js';

// ---------------------------------------------------------------------------
// Type mapping
// ---------------------------------------------------------------------------

const TYPE_MAP: Record<string, string> = {
  string: 'string',
  text: 'string',
  richtext: 'string',
  uid: 'string',
  email: 'string',
  password: 'string',
  date: 'string',
  time: 'string',
  datetime: 'string',
  integer: 'number',
  float: 'number',
  decimal: 'number',
  biginteger: 'string',
  boolean: 'boolean',
  json: 'unknown',
  blocks: 'unknown',
  media: 'unknown',
  relation: 'unknown',
  component: 'unknown',
  dynamiczone: 'unknown[]',
  customField: 'unknown',
};

function attrToTsType(attr: any): string {
  if (attr.type === 'enumeration' && Array.isArray(attr.enum)) {
    return attr.enum.map((v: string) => `'${v}'`).join(' | ');
  }
  return TYPE_MAP[attr.type] || 'unknown';
}

function pascalCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase()
    .split('-')
    .map(s => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

// ---------------------------------------------------------------------------
// Command
// ---------------------------------------------------------------------------

export const generateTypesCommand: CliCommand = {
  name: 'ts:generate-types',
  description: 'Generate TypeScript type definitions from content type schemas',
  action: async (_args, ctx) => {
    try {
      info('Loading content types...');
      const { Apick } = await import('@apick/core');
      const apick = new Apick({ appDir: ctx.cwd });
      await apick.load();

      const contentTypes = apick.contentTypes || {};
      const entries = Object.entries(contentTypes);

      if (entries.length === 0) {
        info('No content types found. Nothing to generate.');
        await apick.destroy();
        return;
      }

      const lines: string[] = [
        '// Auto-generated by @apick/cli — do not edit manually.',
        '// Regenerate with: npx apick ts:generate-types',
        '',
      ];

      for (const [uid, ct] of entries) {
        const name = ct.info?.singularName || uid.split('.').pop() || 'Unknown';
        const interfaceName = pascalCase(name);
        const attrs = ct.attributes || {};

        lines.push(`export interface ${interfaceName} {`);
        lines.push('  id: number;');

        for (const [attrName, attrDef] of Object.entries(attrs) as [string, any][]) {
          const tsType = attrToTsType(attrDef);
          const optional = !attrDef.required ? '?' : '';
          lines.push(`  ${attrName}${optional}: ${tsType};`);
        }

        lines.push('}');
        lines.push('');
      }

      const outDir = join(ctx.cwd, 'types', 'generated');
      const outFile = join(outDir, 'contentTypes.d.ts');
      mkdirSync(outDir, { recursive: true });
      writeFileSync(outFile, lines.join('\n'), 'utf8');

      await apick.destroy();

      success(`Generated ${entries.length} interface(s) at types/generated/contentTypes.d.ts`);
    } catch (err: any) {
      logError(err.message || 'Failed to generate types');
    }
  },
};
