GET http://localhost:3000/posts

###

GET http://localhost:3000/posts/2

###

GET http://localhost:3000/posts?userId=1

###
GET http://localhost:3000/posts?q=post&_sort=userId&_limit=5&_page=2

###
GET http://localhost:3000/posts?id_gte=3&id_lte=10


###

GET http://localhost:3000/users 


###

POST http://localhost:3000/register
Content-Type: application/json

{
  "username" : "reshma",
  "password" : "reshma"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username" : "rahul",
  "password" : "rahul"
}

### Special for admin purpose only

GET http://localhost:3000/__db

###

GET http://localhost:3000/__collections

###
POST http://localhost:3000/__collections
Content-Type: application/json

{
  "name": "new-todos"
}

###

PATCH http://localhost:3000/__collections/todos
Content-Type: application/json

{
  "name": "todos-extra-two"
}

