import Router from "koa-router";
import autoGeneratedControllers from "../controllers/autoGeneratedControllers.js";

export default function dynamicRoutes(database) {
  const router = new Router();

  // Fetch the list of collections from the database
  database.getCollections().then((data) => {
    // Create routes for each collection
    Object.keys(data).forEach((entry) => {
      if (entry) {
        const controller = autoGeneratedControllers(database, entry);

        // Define the routes
        router.get(`/${entry}`, controller.get);
        router.get(`/${entry}/:id`, controller.get);
        router.post(`/${entry}`, controller.post);
        router.put(`/${entry}/:id`, controller.put);
        router.patch(`/${entry}/:id`, controller.patch);
        router.delete(`/${entry}/:id`, controller.del);
      }
    });
  });

  // Return the routes middleware
  return router.routes();
}
