export default function autoGeneratedControllers(database, entry) {
  return {
    get: async (ctx) => {
      ctx.body = await database.getEntries(entry);
    },
    post: async (ctx) => {
      ctx.body = await database.insert(entry, ctx.request.body);
    },
    put: async (ctx) => {
      ctx.body = await database.update(entry, ctx.params.id, ctx.request.body);
    },
    patch: async (ctx) => {
      ctx.body = await database.update(entry, ctx.params.id, ctx.request.body);
    },
    del: async (ctx) => {
      ctx.body = await database.remove(entry, ctx.params.id);
    }
  };
};
