export default function autoGeneratedControllers(database, entry) {
  return {
    getOne: async (ctx) => {
      ctx.body = await database.get(entry,ctx);
    },
    get: async (ctx) => {
      ctx.body = await database.get(entry,ctx);
    },
    post: async (ctx) => {
      ctx.body = await database.insert(entry, ctx.request.body);
    },
    put: async (ctx) => {
      ctx.body = await database.update(entry, ctx.params.id, ctx.request.body);
    },
    patch: async (ctx) => {
      ctx.body = await database.patch(entry, ctx.params.id, ctx.request.body);
    },
    del: async (ctx) => {
      ctx.body = await database.remove(entry, ctx.params.id);
    }
  };
};

// todo: send ctx in all the functions. It can be the responsiblity of the functions
// to extract the value of body, params, id etc.